apiVersion: v1
kind: Secret
metadata:
  name: neuralmesh-secrets
  labels:
    {{- include "neuralmesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_PUBLIC_KEY: {{ .Values.secrets.jwtPublicKey | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secrets.jwtPrivateKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}

